/** Données de test des photos (aucune donnée réelle). */
// Photos 40 × 24 générées pour le test : EXIF (marque, modèle, position GPS), commentaire,
// et données ajoutées après la fin de l'image. Version classique puis progressive.
export const BASELINE_JPEG =
  "/9j/4AAQSkZJRgABAQAAAQABAAD/4QC+RXhpZgAATU0AKgAAAAgAAwEPAAIAAAAQAAAAMgEQAAIAAAANAAAAQoglAAQAAAABAAAA" +
  "UAAAAABNYXJxdWVUZWxlcGhvbmUATW9kZWxlU2VjcmV0AAAABAABAAIAAAACTgAAAAACAAUAAAADAAAAhgADAAIAAAACRQAAAAAE" +
  "AAUAAAADAAAAngAAAAAAAAAwAAAAAQAAADYAAAABAAAAHgAAAAEAAAACAAAAAQAAABoAAAABAAAAKAAAAAH//gATY29tbWVudGFp" +
  "cmUgcHJpdmX/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBwe" +
  "Hx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAAR" +
  "CAAYACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQR" +
  "BRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlq" +
  "c3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP0" +
  "9fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdh" +
  "cRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6" +
  "goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oA" +
  "DAMBAAIRAxEAPwD5isdC6fJ+lbtjoXT5P0rtLHQunyVu2OhdPkrOhijycr4h21OLsdC6fJ+lbtjoXT5P0rtLHQunyVu2OhdPkr2a" +
  "GKP0TK+IdtTirHQunyfpRXqNjoXT5KK9aGK0Pu8NxD7m5ztjoXT5P0rdsdC6fJ+lFFfmlCpI/h7K8bW01N2x0Lp8n6Vu2OhdPk/S" +
  "iivZoVJH6LlmNraam5Y6F0+T9KKKK9aFSVj7vDY2t7Nan//ZTVBGLVRSQUlMSU5HLVNFQ09ORC1JTUFHRS1FeGlm";
export const PROGRESSIVE_JPEG =
  "/9j/4AAQSkZJRgABAQAAAQABAAD/4QC+RXhpZgAATU0AKgAAAAgAAwEPAAIAAAAQAAAAMgEQAAIAAAANAAAAQoglAAQAAAABAAAA" +
  "UAAAAABNYXJxdWVUZWxlcGhvbmUATW9kZWxlU2VjcmV0AAAABAABAAIAAAACTgAAAAACAAUAAAADAAAAhgADAAIAAAACRQAAAAAE" +
  "AAUAAAADAAAAngAAAAAAAAAwAAAAAQAAADYAAAABAAAAHgAAAAEAAAACAAAAAQAAABoAAAABAAAAKAAAAAH//gATY29tbWVudGFp" +
  "cmUgcHJpdmX/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBwe" +
  "Hx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wgAR" +
  "CAAYACgDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAQFBgf/xAAYAQEAAwEAAAAAAAAAAAAAAAAEAgUGB//aAAwDAQAC" +
  "EAMQAAAB8wv2rokxb9q5mixXUF3udeZrh914zRXBd9//xAAWEAADAAAAAAAAAAAAAAAAAAAAAgP/2gAIAQEAAQUCSAkBICQEgJAS" +
  "AkBICQEgJASAkBIH/8QAGhEAAgMBAQAAAAAAAAAAAAAAAAMCBAUSIf/aAAgBAwEBPwGroFXQF6HhVdMrOmLdPk//xAAXEQADAQAA" +
  "AAAAAAAAAAAAAAAAAQID/9oACAECAQE/AY1I1FqRTIpipn//xAAUEAEAAAAAAAAAAAAAAAAAAAAw/9oACAEBAAY/An//xAAVEAEB" +
  "AAAAAAAAAAAAAAAAAAAAYf/aAAgBAQABPyGSSSSSSSSSSSSSST//2gAMAwEAAgADAAAAEJJj4Iwv/8QAGBEBAQEBAQAAAAAAAAAA" +
  "AAAAIQAxEVH/2gAIAQMBAT8QxbFvfCYzcxv/xAAXEQEAAwAAAAAAAAAAAAAAAAAQABEh/9oACAECAQE/ECsmSpP/xAAWEAEBAQAA" +
  "AAAAAAAAAAAAAAAAMcH/2gAIAQEAAT8QjlHKOUco5RYsWLFjlHKOUco5f//ZTVBGLVRSQUlMSU5HLVNFQ09ORC1JTUFHRS1FeGlm";

export const jpegBytes = (base64: string) => new Uint8Array(Buffer.from(base64, "base64"));
